### ISSUE TITLE
Provide an example of how to get the state of DB before enabling CDC

### ISSUE THREAD

**Issue by yurii-pelekh** [DAXGRID/mssql-cdc#75]
Please provide an example of how to get the state of DB before enabling CDC. I know how to implement it in Postgres (using Snapshot, here is a good explanation https://event-driven.io/en/how_to_get_all_messages_through_postgres_logical_replication/).

And thanks for a great library!

**Comment by runeanielsen** [comment]
Hi @agronompele,

Thanks for your message. I'm sorry, but I'm not an expert in SQL-Server CDC and I don't know if it's possible to get the state of the database before enabling CDC. If you find a way to do it, feel free to add it to this issue.

Thanks for using our library and for your appreciation!

**Comment by yurii-pelekh** [comment]
Hi @runeanielsen ,

Thanks for the quick response. Sure, I'll let you know when I find something.

**Comment by runeanielsen** [comment]
@agronompele 

On a side note, my experience with the implementation of Change Data Capture (CDC) in Microsoft SQL Server feels more like a hack compared to the implementation of logical replication in PostgreSQL. I hope there is a way for you to get the state before enabling CDC, but I've had features I would consider essential, but does not exist with CDC.

**Comment by agronompele** [comment]
@runeanielsen 

Yeah, I also have some experience with using Postgres logical replication. It looks very convenient and useful.

As for getting the initial DB state before enabling CDC in MS SQL Server, I think that I can try with the creation of Snapshot and removing it after I handled it https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16
